name: phatsurf
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: app
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/phatsurf
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.0
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data: