name: phatsurf
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: app
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/phatsurf
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
      - internal-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mongo:
    image: mongo:8.0
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  mongo_data:
networks:
  app-network:
    driver: bridge
  internal-network:
    driver: bridge
    internal: true