name: SonarCloud
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 0 * * 1" # Weekly scan at midnight on Monday

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: .python-version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: poetry install --no-interaction --no-ansi --no-root

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: tox

      # Step 4: Prepare SonarCloud Scan
      - name: Read Python Version
        id: python-version
        run: |
          echo "version=$(cat .python-version || echo "3.13")" >> $GITHUB_OUTPUT
        shell: bash

      # Step 5: SonarCloud Scan using official action
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
            -Dsonar.python.version=${{ steps.python-version.outputs.version }}
